spring:
  profiles:
    active:
      - dev
  activiti:
    check-process-definitions: false
    #保存历史数据级别设置为full最高级别，便于历史数据的追溯
    history-level: full
    db-history-used: true
    database-schema-update: true
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  jackson:
    serialization:
      write-dates-as-timestamps: true
      indent_output: true
    time-zone: Asia/Shanghai
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: top.dongxibao.**.entity
  configuration:
    jdbc-type-for-null: 'null'
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      logic-delete-field: del_flag  #全局逻辑删除字段值 3.3.0开始支持
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: assign_id
      capital-mode: true
      #数据库类型
      db-type: mysql
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

