server:
  port: 10000
  servlet:
    # 应用的访问路径
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # SqlServer 配置
    url: jdbc:mysql://localhost:3306/small_erp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 密码
    # password:

logging:
  level:
    top.dongxibao.erp: debug
  file:
    path: ./logs
    max-history: 30 # 日志文件存放的日期，单位：Day（天）

knife4j:
  enable: true
  setting:
    # Knife4j默认显示中文(zh-CN),如果开发者想直接显示英文(en-US)，在通过该配置进行设置即可
    language: zh-CN

aliyun:
  oss:
    endpoint: oss-cn-qingdao.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: test # 访问身份验证中用到用户标识
    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: dxb-test01 # oss的存储空间
    maxSize: 10 # 上传文件大小(M)
    dir:
      prefix: small/images/ # 上传文件夹路径前缀

